name: ipr
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  checkdigit: ^0.3.1
  pinput: ^2.2.11
  cloud_firestore: ^3.4.0
  firebase_auth: ^3.5.0
  firebase_core: ^1.20.0
  flutter_svg: ^1.0.1
  flutter:
    sdk: flutter
  fluttertoast: ^8.0.8
  google_fonts:
  intl: ^0.17.0
  datetime_picker_formfield: ^2.0.1
  webview_flutter: ^3.0.4


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  hexcolor: ^2.0.4
  font_awesome_flutter: ^9.1.0
  otp_text_field: ^1.1.1
  flutter_form_builder: ^7.6.0
  geolocator: ^8.2.0  
  google_maps_flutter: ^2.1.3
  flutter_icons: ^1.1.0
  keyboard_avoider: ^0.1.2
  splashscreen:
  timeago: ^3.3.0
  simple_gradient_text: ^1.2.3
  carousel_slider: ^4.1.1
  razorpay_flutter: ^1.3.2
  youtube_player_flutter: ^8.1.0
  easy_localization: ^3.0.1
  file_picker: ^5.0.1
  firebase_storage: ^10.3.6
  country_state_city_picker: ^1.2.8
  country_state_city_pro: ^0.0.3
  geocoder: ^0.2.1

  syncfusion_flutter_pdfviewer: ^20.2.45-beta





dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/translations/
    - assets/images/
    - assets/images/splashscreen/
    - assets/images/logo.svg
    - assets/images/man.svg
    - assets/images/weekone.jpg
    - assets/images/weektwo.jpg
    - assets/images/drakeone.jpg
    - assets/images/draketwo.jpg
    - assets/images/AgentSearchPic.png
    - assets/images/map.png
    - assets/images/pin.png
    - assets/images/city.png
    - assets/images/locman.png
    - assets/images/pinman.png
    - assets/images/cityman.png
    - assets/images/raisepic.png
    - assets/images/newapp.png
    - assets/images/subapp.png
    - assets/images/guide.png
    - assets/images/faqq.png
    - assets/images/xyz4.jpg
    - assets/images/xyz3.jpg
    - assets/images/xyz2.jpg
    - assets/images/xyz.jpg
    - assets/images/xyz5.jpg
    - assets/images/copy.jpg
    - assets/images/patentFile.jpg
    - assets/images/phone.jpg
    - assets/images/arrowRight.png
    - assets/images/copy.jpg
    - assets/images/phone.jpg
    - assets/images/help.png
    - assets/images/objections.png
    - assets/images/placeholder.png
    - assets/images/propic.png
    - assets/images/tweet1.jpeg
    - assets/images/tweet2.jpeg
    - assets/images/profilePicnew.jpg
    - assets/images/marketPlace.png




  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
