
const chatDetails = [
  {
    "id": 1,
    "isMe": false,
    "profile": "https://i.pinimg.com/originals/cd/63/95/cd63958613ce86afc242b1bcc5812bba.jpg",
    "message": "Hey mate!",
    "messageNo": 1,
  },
  {
    "id": 2,
    "isMe": false,
    "profile": "https://i.pinimg.com/originals/cd/63/95/cd63958613ce86afc242b1bcc5812bba.jpg",
    "message": "How are you doing?",
    "messageNo": 3,
  },
  {
    "id": 3,
    "isMe": true,
    "profile": "",
    "message": "Hi!",
    "messageNo": 1,
  },
  {
    "id": 4,
    "isMe": true,
    "profile": "",
    "message": "Fine.",
    "messageNo": 2,
  },
  {
    "id": 5,
    "isMe": true,
    "profile": "",
    "message": "ok ok ",
    "messageNo": 3,
  },
  {
    "id": 6,
    "isMe": false,
    "profile": "https://i.pinimg.com/originals/cd/63/95/cd63958613ce86afc242b1bcc5812bba.jpg",
    "message": "some random chats",
    "messageNo": 0,
  },
  {
    "id": 6,
    "isMe": true,
    "profile": "",
    "message": "dont know what to write",
    "messageNo": 1,
  },
  {
    "id": 6,
    "isMe": true,
    "profile": "",
    "message": "😒😒😒",
    "messageNo": 3,
  },
  {
    "id": 7,
    "isMe": false,
    "profile": "https://i.pinimg.com/originals/cd/63/95/cd63958613ce86afc242b1bcc5812bba.jpg",
    "message": "AKGEc",
    "messageNo": 1,
  },
  {
    "id": 8,
    "isMe": false,
    "profile": "https://i.pinimg.com/originals/cd/63/95/cd63958613ce86afc242b1bcc5812bba.jpg",
    "message": "Team conatus",
    "messageNo": 3,
  },
  {
    "id": 9,
    "isMe": true,
    "profile": "",
    "message": "hmm",
    "messageNo": 1,
  },
  {
    "id": 10,
    "isMe": true,
    "profile": "",
    "message": "random stuff",
    "messageNo": 3,
  },
  {
    "id": 11,
    "isMe": false,
    "profile": "https://i.pinimg.com/originals/cd/63/95/cd63958613ce86afc242b1bcc5812bba.jpg",
    "message": "just want to fill the chats bubble",
    "messageNo": 0,
  },
  {
    "id": 12,
    "isMe": true,
    "profile": "",
    "message": "Okay",
    "messageNo": 0,
  },
];